"""LLM offload GRPO reward for slime (math + cost-aware GLM handoff).

Adapted from ``pyroDash-training/train_test/phase2/reward.py``.

When a completion contains ``<|llm_offload|>``, the remainder is generated by a
remote chat API (default: GLM-5.2). Score:

    score = (1 if correct else 0)
            - λ * cost_ratio
            + w_fmt * think_format
            - w_len * think_length_penalty

where ``cost_ratio = Cost_actual / Cost_baseline`` and baseline comes from
dataset ``metadata.usage`` (GLM-only prompt/completion tokens).

Wire with::

    --group-rm
    --custom-rm-path examples.llm_offload.reward.reward_func
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

import requests

from slime.rollout.rm_hub.math_utils import grade_answer_verl
from slime.utils.types import Sample

logger = logging.getLogger(__name__)

OFFLOAD_TAG = "<|llm_offload|>"
REDIRECT_END = "<|im_end|>"
DEFAULT_DASHSCOPE_BASE_URL = os.environ.get("DASHSCOPE_BASE_URL", "http://127.0.0.1:8000/v1")
DEFAULT_DASHSCOPE_MODEL = os.environ.get("DASHSCOPE_MODEL", "glm-5.2-fp8")
DEFAULT_OFFLOAD_MAX_TOKENS = int(os.environ.get("OFFLOAD_MAX_TOKENS", "8192"))
MAX_CALL_NUM = 8192
DEFAULT_LOG_PREVIEW_CHARS = 400
COST_SMALL_PROMPT = 0.017
COST_SMALL_OUTPUT = 0.026
COST_GLM_INPUT = 0.315
COST_GLM_OUTPUT = 1.0
THINK_FORMAT_WEIGHT = 0.05
THINK_LENGTH_WEIGHT = 0.05

_REWARD_BATCH_STEP = 0

_FORMAT_RE = re.compile(
    r"<think>.*</think>.*\\boxed\{.*\}.*",
    flags=re.DOTALL,
)
_THINK_BLOCK_RE = re.compile(r"<think>(.*?)</think>", flags=re.DOTALL)
_TAG_WHITESPACE_RE = re.compile(r"\s*(<|>|/)\s*")

DEFAULT_REMOTE_HANDOFF_PROMPT = (
    "You are a helpful assistant completing a task that was partially solved "
    "by a smaller local model before offload.\n"
    "Collaborative handoff protocol:\n"
    "- The assistant message may contain <part_think>...</part_think> with reasoning "
    "the small model already produced before offload.\n"
    "- Because part of the reasoning is already in <part_think>, continue from "
    "where it stopped: your reasoning channel should pick up at the first "
    "unresolved step and carry forward to the final answer. Do not repeat, "
    "paraphrase, or re-derive anything already present in <part_think>.\n"
    "- If <part_think> already concludes the task, proceed directly to the final answer.\n"
    "- Put the user-facing answer only in normal assistant content. Never quote "
    "or mention <part_think> to the user.\n"
    "- <part_think> is an internal marker, not user input."
)


def _is_main_process() -> bool:
    return os.environ.get("LOCAL_RANK", os.environ.get("RANK", "0")) in ("0", "-1")


def _truncate(text: str, max_chars: int) -> str:
    if max_chars <= 0 or len(text) <= max_chars:
        return text
    return f"[+{len(text) - max_chars} chars]..." + text[-(max_chars):]


def _emit_offload_log(message: str) -> None:
    if not _is_main_process():
        return
    print(message, flush=True)
    logger.info(message)


def _normalize_response(text: str) -> str:
    return _TAG_WHITESPACE_RE.sub(r"\1", text)


def _offload_prefix(raw: str) -> str:
    offload_idx = raw.find(OFFLOAD_TAG)
    prefix = raw[:offload_idx] if offload_idx >= 0 else raw
    return prefix.replace(OFFLOAD_TAG, "").replace(REDIRECT_END, "")


def _extract_user_content(prompt: Any) -> str:
    if isinstance(prompt, list):
        parts: list[str] = []
        for msg in prompt:
            if not isinstance(msg, dict) or msg.get("role") != "user":
                continue
            content = msg.get("content", "")
            if isinstance(content, list):
                texts = [
                    str(part.get("text", ""))
                    for part in content
                    if isinstance(part, dict) and part.get("type") == "text"
                ]
                parts.append("\n".join(texts))
            else:
                parts.append(str(content))
        return "\n".join(parts).strip()
    return str(prompt).strip()


def _prompt_from_sample(sample: Sample) -> Any:
    """Prefer original chat messages from metadata; fall back to rendered prompt."""
    md = sample.metadata if isinstance(sample.metadata, dict) else {}
    if "messages" in md:
        return md["messages"]
    if "prompt_messages" in md:
        return md["prompt_messages"]
    return sample.prompt


def _estimate_tokens(text: str) -> int:
    return max(0, len(text) // 4)


def _usage_token_counts(usage: dict[str, Any] | None) -> tuple[int, int]:
    prompt_tokens_avg = 108
    completion_tokens_avg = 4615
    if not usage:
        return prompt_tokens_avg, completion_tokens_avg
    return int(usage.get("prompt_tokens", prompt_tokens_avg) or prompt_tokens_avg), int(
        usage.get("completion_tokens", completion_tokens_avg) or completion_tokens_avg
    )


def _baseline_glm_cost(usage: dict[str, Any] | None) -> float:
    prompt_tokens, completion_tokens = _usage_token_counts(usage)
    return prompt_tokens * COST_GLM_INPUT + completion_tokens * COST_GLM_OUTPUT


def _actual_cost(
    *,
    small_prompt_tokens: int,
    small_output_tokens: int,
    glm_input_tokens: int,
    glm_output_tokens: int,
) -> float:
    return (
        small_prompt_tokens * COST_SMALL_PROMPT
        + small_output_tokens * COST_SMALL_OUTPUT
        + glm_input_tokens * COST_GLM_INPUT
        + glm_output_tokens * COST_GLM_OUTPUT
    )


def _cost_ratio(actual_cost: float, baseline_cost: float) -> float:
    if baseline_cost <= 0:
        return 0.0
    return actual_cost / baseline_cost


def _extract_think_content(text: str) -> str:
    normalized = _normalize_response(text)
    match = _THINK_BLOCK_RE.search(normalized)
    return match.group(1).strip() if match else ""


def _glm_max_tokens(total_budget: int, small_output_tokens: int) -> int:
    return max(0, total_budget - small_output_tokens)


def _build_offload_messages(prompt: Any, response: str) -> list[dict[str, str]]:
    user_content = _extract_user_content(prompt)
    assistant_partial = _offload_prefix(response).strip()
    messages: list[dict[str, str]] = [
        {"role": "system", "content": DEFAULT_REMOTE_HANDOFF_PROMPT},
        {"role": "user", "content": user_content},
    ]
    if assistant_partial:
        cleaned = assistant_partial.replace("<think>", "").replace("</think>", "")
        messages.append({"role": "assistant", "content": f"<part_think>{cleaned}</part_think>"})
    return messages


def _call_remote_chat(
    messages: list[dict[str, str]],
    *,
    api_key: str,
    base_url: str,
    model: str,
    max_tokens: int,
    timeout: float = 600.0,
    enable_thinking: bool = True,
) -> tuple[str, str, dict[str, Any] | None]:
    if not api_key:
        return "[Error: DASHSCOPE_API_KEY not set]", "", None

    url = f"{base_url.rstrip('/')}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "chat_template_kwargs": {"enable_thinking": enable_thinking},
    }

    try:
        response = requests.post(url, headers=headers, json=body, timeout=timeout)
        if response.status_code != 200:
            return f"[Error: status {response.status_code}: {response.text}]", "", None
        data = response.json()
        message = data["choices"][0].get("message", {})
        think = str(message.get("reasoning") or message.get("reasoning_content") or "")
        content = str(message.get("content") or "")
        usage = data.get("usage")
        if usage is not None and not isinstance(usage, dict):
            usage = None
        return content, think, usage
    except Exception as exc:
        return f"[Error: remote call failed: {exc}]", "", None


def _complete_offload_response(
    response: str,
    prompt: Any,
    *,
    api_key: str,
    base_url: str,
    model: str,
    max_tokens: int,
    enable_thinking: bool = True,
) -> tuple[str, dict[str, Any] | None]:
    if OFFLOAD_TAG not in response or max_tokens <= 0:
        return response, None

    messages = _build_offload_messages(prompt, response)
    generated, think, usage = _call_remote_chat(
        messages,
        api_key=api_key,
        base_url=base_url,
        model=model,
        max_tokens=max_tokens,
        enable_thinking=enable_thinking,
    )
    prefix = _offload_prefix(response)
    cleaned_prefix = prefix.replace("<think>", "").replace("</think>", "")
    res = f"<think>{cleaned_prefix}{think}</think>{generated}"
    return res, usage


def _complete_offload_batch(
    responses: list[str],
    prompts: list[Any],
    *,
    api_key: str,
    base_url: str,
    model: str,
    max_tokens: int,
    max_workers: int,
    small_output_tokens: list[int],
    enable_thinking: bool = True,
) -> tuple[list[str], list[dict[str, Any] | None]]:
    indices = [i for i, resp in enumerate(responses) if OFFLOAD_TAG in resp]
    completed = list(responses)
    usages: list[dict[str, Any] | None] = [None] * len(responses)
    if not indices:
        return completed, usages

    workers = max(1, min(max_workers, len(indices)))

    def _run(idx: int) -> tuple[int, str, dict[str, Any] | None]:
        glm_max = _glm_max_tokens(max_tokens, small_output_tokens[idx])
        full, usage = _complete_offload_response(
            responses[idx],
            prompts[idx],
            api_key=api_key,
            base_url=base_url,
            model=model,
            max_tokens=glm_max,
            enable_thinking=enable_thinking,
        )
        return idx, full, usage

    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(_run, idx) for idx in indices]
        for future in as_completed(futures):
            idx, full, usage = future.result()
            completed[idx] = full
            usages[idx] = usage
    return completed, usages


def format_reward(response: str) -> float:
    normalized = _normalize_response(response)
    return 1.0 if _FORMAT_RE.fullmatch(normalized) else 0.0


def accuracy_reward(response: str, ground_truth: str) -> float:
    return 1.0 if grade_answer_verl(response, ground_truth) else 0.0


def think_format_reward(raw_response: str) -> float:
    prefix = _offload_prefix(raw_response)
    normalized = _normalize_response(prefix)
    matches = list(_THINK_BLOCK_RE.finditer(normalized))
    if len(matches) != 1:
        return 0.0
    return 1.0 if matches[0].group(1).strip() else 0.0


def think_length_penalty(raw_response: str, reference_think: str | None) -> float:
    if not reference_think or not str(reference_think).strip():
        return 0.0
    think_text = _extract_think_content(_offload_prefix(raw_response))
    actual_tokens = _estimate_tokens(think_text)
    reference_tokens = _estimate_tokens(str(reference_think).strip())
    if reference_tokens <= 0:
        return 0.0
    ratio = actual_tokens / reference_tokens
    if ratio <= 1.0:
        return 0.0
    return min(1.0, ratio - 1.0)


def _glm_token_counts(
    *,
    if_call: bool,
    glm_usage: dict[str, Any] | None,
    completed_response: str,
    raw_response: str,
) -> tuple[int, int]:
    if not if_call:
        return 0, 0
    prompt_tokens, completion_tokens = _usage_token_counts(glm_usage)
    if prompt_tokens or completion_tokens:
        return prompt_tokens, completion_tokens
    prefix = _offload_prefix(raw_response)
    if completed_response.startswith(prefix):
        glm_portion = completed_response[len(prefix) :]
    else:
        glm_portion = completed_response
    return _estimate_tokens(prefix), _estimate_tokens(glm_portion)


def _overall_score(
    *,
    is_correct: bool,
    cost_ratio: float,
    think_format_score: float,
    think_length_penalty_val: float,
    efficiency_lambda: float,
    think_format_weight: float,
    think_length_weight: float,
) -> float:
    base = 1.0 if is_correct else 0.0
    return (
        base
        - efficiency_lambda * cost_ratio
        + think_format_weight * think_format_score
        - think_length_weight * think_length_penalty_val
    )


def _log_batch_summary(
    *,
    batch_step: int,
    raw_responses: list[str],
    completed_responses: list[str],
    processed: list[dict[str, Any]],
    scores: list[float],
    model: str,
    preview_chars: int,
) -> None:
    if not _is_main_process():
        return
    n = len(raw_responses)
    offload_count = sum(1 for item in processed if item["if_call"])
    correct_count = sum(1 for item in processed if item["is_correct"])
    mean_cost = sum(item["cost_ratio"] for item in processed) / n if processed else 0.0
    mean_score = sum(scores) / len(scores) if scores else 0.0
    _emit_offload_log(
        f"[llm_offload] batch={batch_step} n={n} offload={offload_count}/{n} "
        f"correct={correct_count}/{n} mean_cost_ratio={mean_cost:.3f} "
        f"mean_score={mean_score:.3f} glm_model={model}"
    )
    for idx, (raw, completed, item, score) in enumerate(
        zip(raw_responses, completed_responses, processed, scores)
    ):
        _emit_offload_log(
            f"[llm_offload] batch={batch_step} sample={idx + 1}/{n} "
            f"offload={item['if_call']} cost_ratio={item['cost_ratio']:.3f} "
            f"think_fmt={item['think_format_score']:.2f} "
            f"think_len_pen={item['think_length_penalty']:.2f} "
            f"correct={item['is_correct']} score={score:.3f}"
        )
        if item["if_call"]:
            _emit_offload_log(
                f"[llm_offload]   small_model ({len(raw)} chars):\n{_truncate(raw, preview_chars)}"
            )
            prefix = _offload_prefix(raw)
            glm_portion = completed[len(prefix) :] if completed.startswith(prefix) else completed
            _emit_offload_log(
                f"[llm_offload]   large_model ({len(glm_portion)} chars, {model}):\n"
                f"{_truncate(glm_portion, preview_chars)}"
            )


def _score_batch(
    *,
    raw_responses: list[str],
    prompts: list[Any],
    labels: list[str],
    usages: list[Any],
    thinks: list[Any],
    small_prompt_tokens: list[int],
    small_output_tokens: list[int],
    efficiency_lambda: float,
    think_format_weight: float,
    think_length_weight: float,
    api_key: str,
    base_url: str,
    model: str,
    offload_max_tokens: int,
    offload_max_workers: int,
    preview_chars: int,
) -> list[float]:
    global _REWARD_BATCH_STEP
    _REWARD_BATCH_STEP += 1
    batch_step = _REWARD_BATCH_STEP

    completed_responses, glm_usages = _complete_offload_batch(
        raw_responses,
        prompts,
        api_key=api_key,
        base_url=base_url,
        model=model,
        max_tokens=offload_max_tokens,
        max_workers=offload_max_workers,
        small_output_tokens=small_output_tokens,
        enable_thinking=True,
    )

    processed: list[dict[str, Any]] = []
    scores: list[float] = []
    for idx, (raw, completed, gt, prompt) in enumerate(
        zip(raw_responses, completed_responses, labels, prompts)
    ):
        if_call = OFFLOAD_TAG in raw
        acc = accuracy_reward(completed, gt)
        is_correct = acc > 0.5
        think_fmt = think_format_reward(raw)
        think_len_pen = think_length_penalty(raw, thinks[idx])
        glm_in, glm_out = _glm_token_counts(
            if_call=if_call,
            glm_usage=glm_usages[idx],
            completed_response=completed,
            raw_response=raw,
        )
        actual = _actual_cost(
            small_prompt_tokens=small_prompt_tokens[idx],
            small_output_tokens=small_output_tokens[idx],
            glm_input_tokens=glm_in,
            glm_output_tokens=glm_out,
        )
        baseline = _baseline_glm_cost(usages[idx] if isinstance(usages[idx], dict) else None)
        ratio = _cost_ratio(actual, baseline)
        item = {
            "if_call": if_call,
            "is_correct": is_correct,
            "cost_ratio": ratio,
            "think_format_score": think_fmt,
            "think_length_penalty": think_len_pen,
        }
        processed.append(item)
        scores.append(
            float(
                _overall_score(
                    is_correct=is_correct,
                    cost_ratio=ratio,
                    think_format_score=think_fmt,
                    think_length_penalty_val=think_len_pen,
                    efficiency_lambda=efficiency_lambda,
                    think_format_weight=think_format_weight,
                    think_length_weight=think_length_weight,
                )
            )
        )

    _log_batch_summary(
        batch_step=batch_step,
        raw_responses=raw_responses,
        completed_responses=completed_responses,
        processed=processed,
        scores=scores,
        model=model,
        preview_chars=preview_chars,
    )
    return scores


async def reward_func(args, samples: list[Sample], **kwargs) -> list[float]:
    """Batch reward entrypoint for slime ``--group-rm --custom-rm-path``."""
    if not isinstance(samples, list):
        samples = [samples]

    efficiency_lambda = float(
        os.environ.get("OFFLOAD_EFFICIENCY_LAMBDA", getattr(args, "offload_efficiency_lambda", None) or "0.6")
    )
    think_format_weight = float(os.environ.get("OFFLOAD_THINK_FORMAT_WEIGHT", str(THINK_FORMAT_WEIGHT)))
    think_length_weight = float(os.environ.get("OFFLOAD_THINK_LENGTH_WEIGHT", str(THINK_LENGTH_WEIGHT)))
    api_key = os.environ.get("DASHSCOPE_API_KEY", "")
    base_url = os.environ.get("DASHSCOPE_BASE_URL", DEFAULT_DASHSCOPE_BASE_URL)
    model = os.environ.get("DASHSCOPE_MODEL", DEFAULT_DASHSCOPE_MODEL)
    offload_max_tokens = int(os.environ.get("OFFLOAD_MAX_TOKENS", str(DEFAULT_OFFLOAD_MAX_TOKENS)))
    offload_max_workers = int(os.environ.get("OFFLOAD_MAX_WORKERS", "32"))
    preview_chars = int(os.environ.get("OFFLOAD_LOG_PREVIEW_CHARS", str(DEFAULT_LOG_PREVIEW_CHARS)))

    raw_responses: list[str] = []
    prompts: list[Any] = []
    labels: list[str] = []
    usages: list[Any] = []
    thinks: list[Any] = []
    small_prompt_tokens: list[int] = []
    small_output_tokens: list[int] = []

    for sample in samples:
        md = sample.metadata if isinstance(sample.metadata, dict) else {}
        raw_responses.append(sample.response or "")
        prompts.append(_prompt_from_sample(sample))
        labels.append("" if sample.label is None else str(sample.label))
        usages.append(md.get("usage"))
        thinks.append(md.get("think"))
        # prompt tokens ≈ total - response; fall back to char estimate
        resp_len = int(getattr(sample, "response_length", 0) or 0)
        total_len = len(sample.tokens) if getattr(sample, "tokens", None) else 0
        prompt_len = max(1, total_len - resp_len) if total_len else max(1, _estimate_tokens(str(sample.prompt or "")))
        small_prompt_tokens.append(prompt_len)
        small_output_tokens.append(resp_len if resp_len > 0 else _estimate_tokens(sample.response or ""))

    return await asyncio.to_thread(
        _score_batch,
        raw_responses=raw_responses,
        prompts=prompts,
        labels=labels,
        usages=usages,
        thinks=thinks,
        small_prompt_tokens=small_prompt_tokens,
        small_output_tokens=small_output_tokens,
        efficiency_lambda=efficiency_lambda,
        think_format_weight=think_format_weight,
        think_length_weight=think_length_weight,
        api_key=api_key,
        base_url=base_url,
        model=model,
        offload_max_tokens=offload_max_tokens,
        offload_max_workers=offload_max_workers,
        preview_chars=preview_chars,
    )


__all__ = ["reward_func", "OFFLOAD_TAG", "accuracy_reward", "format_reward"]
